const mode=new URLSearchParams(location.search).get('mode')||'random';
const $=id=>document.getElementById(id);let all=[],queue=[],index=0,answers=[],timerId=null,remaining=2100,submitted=false;
const info={random:['RANDOM PRACTICE','랜덤 10문제','단일·복수 선택 문제를 풀고 즉시 해설을 확인합니다.'],exam:['MOCK EXAM','AZ-900 모의고사','30문제 · 35분 · 제출한 뒤 채점합니다.'],wrong:['REVIEW','오답노트','이전에 틀린 문제만 다시 풉니다.']};
const correctSet=q=>new Set(q.answers||[q.answer]);
const sameSet=(a,b)=>a.size===b.size&&[...a].every(v=>b.has(v));
const isCorrect=(q,a)=>Boolean(a)&&sameSet(new Set(a.choices),correctSet(q));
const letters=q=>[...correctSet(q)].sort((a,b)=>a-b).map(i=>String.fromCharCode(65+i)).join(', ');
const easyHelp=q=>{
  const guides={'공유 책임':'아파트에 비유하면 건물 안전은 Azure가, 집 안 데이터와 출입 관리는 고객이 맡습니다. SaaS로 갈수록 Azure의 관리 범위가 넓어집니다.','서비스 모델':'IaaS는 빈 사무실을 직접 꾸미는 것, PaaS는 시설이 준비된 공유 오피스, SaaS는 완성된 서비스를 바로 쓰는 것에 가깝습니다.','비용':'Azure 비용은 크기·사용 시간·저장량·송신 데이터·리전에 따라 달라집니다. VM을 꺼도 남은 디스크에는 비용이 들 수 있습니다.','Policy':'Policy는 무엇을 배포할 수 있는지 정하는 규칙입니다. 누가 작업할 수 있는지를 정하는 RBAC와 구분하세요.','RBAC':'RBAC는 출입증과 같습니다. 사용자에게 역할을 주고 구독·리소스 그룹·리소스 중 적용 범위를 정합니다.','스토리지':'Blob은 파일 창고, Files는 네트워크 드라이브, Queue는 업무 쪽지함, Disk는 VM 하드디스크라고 생각하면 쉽습니다.','네트워크 보안':'NSG는 서브넷·NIC 앞의 출입 규칙표이고 Azure Firewall은 여러 네트워크를 중앙에서 검사하는 방화벽입니다.','SLA':'SLA는 속도가 아니라 사용 가능 시간에 대한 약속입니다. 서로 의존하는 서비스는 가용성을 곱하므로 전체 SLA가 낮아집니다.','가용성 영역':'가용성 영역은 같은 리전 안의 독립 데이터센터입니다. 리전 전체 장애에는 여러 리전 구성이 필요합니다.','Service Health':'Azure Status는 전 세계 현황판이고 Service Health는 내 구독에 영향을 주는 장애·유지관리 알림판입니다.','조건부 액세스':'사용자, 위치, 장치 상태와 위험 신호를 보고 MFA를 요구하거나 접근을 차단하는 로그인 문지기입니다.','Key Vault':'애플리케이션 암호·인증서·키를 코드 밖의 금고에 보관해 배포 중 비밀 노출을 막습니다.','Monitor':'Azure Monitor는 관측 데이터의 큰 우산입니다. Log Analytics는 로그 질의, Application Insights는 앱 성능 분석에 특화됩니다.','서버리스':'실제 서버는 있지만 사용자가 서버를 만들거나 패치하지 않습니다. 이벤트와 실행량 중심으로 이해하면 됩니다.'};
  return guides[q.topic]||guides[Object.keys(guides).find(k=>q.topic.includes(k))]||'서비스 이름보다 누가 관리하는지, 어느 범위에 적용되는지, 어떤 문제를 해결하는지를 먼저 구분하세요.';
};
async function init(){[$('modeKicker').textContent,$('modeTitle').textContent,$('modeDesc').textContent]=info[mode]||info.random;try{all=await loadQuestions()}catch(e){return fail(e.message)}if(mode==='wrong'){const ids=new Set(getWrongIds());queue=shuffle(all.filter(q=>ids.has(q.id)));if(!queue.length)return fail('저장된 오답이 없습니다.')}else queue=shuffle(all).slice(0,mode==='exam'?30:10);answers=Array(queue.length).fill(null);$('quizBar').hidden=false;if(mode==='exam')startTimer();render()}
function render(){const q=queue[index],a=answers[index],multi=Array.isArray(q.answers),locked=a?.locked&&mode!=='exam';$('progressText').textContent=`${index+1} / ${queue.length}`;$('scoreText').textContent=mode==='exam'?'답안은 제출 후 공개':`정답 ${queue.filter((x,i)=>isCorrect(x,answers[i])).length}`;$('progressFill').style.width=`${(index+1)/queue.length*100}%`;$('quizArea').innerHTML=`<article class="question"><div class="qmeta"><span>${q.domain}</span><span>${q.topic}</span><span>덤프 Q${q.sourceQuestion}</span>${multi?'<span>복수 선택</span>':''}</div><div class="qnum">QUESTION ${String(index+1).padStart(2,'0')}</div><h2>${q.question}</h2>${multi?'<p class="multi-note">정답을 모두 선택한 뒤 선택 확정을 누르세요.</p>':''}<div class="choices">${q.choices.map((c,i)=>`<button data-i="${i}" class="${a?.choices?.includes(i)?'selected':''}" ${locked?'disabled':''}><i>${String.fromCharCode(65+i)}</i><span>${c}</span></button>`).join('')}</div>${multi&&!locked&&mode!=='exam'?'<button class="confirm-answer" id="confirmAnswer">선택 확정</button>':''}${locked?feedback(q,a):''}<div class="qnav"><button class="btn ghost" id="prev" ${index===0?'disabled':''}>이전</button>${index===queue.length-1?`<button class="btn" id="submit">${mode==='exam'?'답안 제출':'결과 보기'}</button>`:`<button class="btn" id="next">다음</button>`}</div></article>`;document.querySelectorAll('.choices button').forEach(b=>b.onclick=()=>choose(+b.dataset.i));const c=$('confirmAnswer');if(c)c.onclick=confirmMulti;$('prev').onclick=()=>{index--;render()};const n=$('next');if(n)n.onclick=()=>{index++;render()};const s=$('submit');if(s)s.onclick=submit}
function choose(choice){const q=queue[index],multi=Array.isArray(q.answers);if(multi){const selected=new Set(answers[index]?.choices||[]);selected.has(choice)?selected.delete(choice):selected.add(choice);answers[index]={choices:[...selected],locked:mode==='exam'}}else{answers[index]={choices:[choice],locked:mode!=='exam'};if(mode!=='exam')setWrong(q.id,!isCorrect(q,answers[index]))}render()}
function confirmMulti(){const q=queue[index],a=answers[index];if(!a?.choices.length)return;answers[index]={...a,locked:true};setWrong(q.id,!isCorrect(q,answers[index]));render()}
function feedback(q,a){const ok=isCorrect(q,a);return `<div class="feedback ${ok?'ok':'no'}"><b>${ok?'정답입니다':`오답입니다 · 정답 ${letters(q)}`}</b><p>${q.explanation}</p><small><b>비전공자 설명</b> ${easyHelp(q)}</small></div>`}
function submit(){if(submitted)return;submitted=true;clearInterval(timerId);queue.forEach((q,i)=>setWrong(q.id,!isCorrect(q,answers[i])));const correct=queue.filter((q,i)=>isCorrect(q,answers[i])).length,pct=Math.round(correct/queue.length*100);if(mode==='exam')saveHistory({date:new Date().toISOString(),correct,total:queue.length,pct});$('quizArea').hidden=true;$('quizBar').hidden=true;$('timer').hidden=true;$('resultArea').hidden=false;$('resultArea').innerHTML=`<p class="eyebrow">RESULT</p><h2>${correct} / ${queue.length}</h2><strong class="result-score">${pct}점</strong><p>${pct>=70?'합격 기준을 넘었습니다.':'70점을 목표로 오답을 복습하세요.'}</p><div class="result-list">${queue.map((q,i)=>`<details class="${isCorrect(q,answers[i])?'pass':'miss'}"><summary>${i+1}. ${q.question}<b>${isCorrect(q,answers[i])?'정답':'오답'}</b></summary><p>덤프 Q${q.sourceQuestion} · 정답: ${letters(q)}</p><p>${q.explanation}</p></details>`).join('')}</div><div class="actions"><a class="btn" href="quiz.html?mode=${mode}">다시 풀기</a><a class="btn ghost" href="quiz.html?mode=wrong">오답 복습</a></div>`}
function startTimer(){$('timer').hidden=false;tick();timerId=setInterval(()=>{remaining--;tick();if(remaining<=0)submit()},1000)}function tick(){const m=String(Math.floor(remaining/60)).padStart(2,'0'),s=String(remaining%60).padStart(2,'0');$('timerText').textContent=`${m}:${s}`}
function fail(msg){$('quizArea').innerHTML=`<div class="empty"><h2>학습을 시작할 수 없습니다</h2><p>${msg}</p><a class="btn" href="index.html">홈으로</a></div>`}init();
