const mode=new URLSearchParams(location.search).get('mode')||'random';
const $=id=>document.getElementById(id);let all=[],queue=[],index=0,answers=[],timerId=null,remaining=2100,submitted=false;
const info={random:['RANDOM PRACTICE','랜덤 10문제','단일·복수 선택 문제를 풀고 즉시 해설을 확인합니다.'],exam:['MOCK EXAM','AZ-900 모의고사','30문제 · 35분 · 제출한 뒤 채점합니다.'],wrong:['REVIEW','오답노트','이전에 틀린 문제만 다시 풉니다.']};
const correctSet=q=>new Set(q.answers||[q.answer]);
const sameSet=(a,b)=>a.size===b.size&&[...a].every(v=>b.has(v));
const isCorrect=(q,a)=>Boolean(a)&&sameSet(new Set(a.choices),correctSet(q));
const letters=q=>[...correctSet(q)].sort((a,b)=>a-b).map(i=>String.fromCharCode(65+i)).join(', ');
async function init(){[$('modeKicker').textContent,$('modeTitle').textContent,$('modeDesc').textContent]=info[mode]||info.random;try{all=await loadQuestions()}catch(e){return fail(e.message)}if(mode==='wrong'){const ids=new Set(getWrongIds());queue=shuffle(all.filter(q=>ids.has(q.id)));if(!queue.length)return fail('저장된 오답이 없습니다.')}else queue=shuffle(all).slice(0,mode==='exam'?30:10);answers=Array(queue.length).fill(null);$('quizBar').hidden=false;if(mode==='exam')startTimer();render()}
function render(){const q=queue[index],a=answers[index],multi=Array.isArray(q.answers),locked=a?.locked&&mode!=='exam';$('progressText').textContent=`${index+1} / ${queue.length}`;$('scoreText').textContent=mode==='exam'?'답안은 제출 후 공개':`정답 ${queue.filter((x,i)=>isCorrect(x,answers[i])).length}`;$('progressFill').style.width=`${(index+1)/queue.length*100}%`;$('quizArea').innerHTML=`<article class="question"><div class="qmeta"><span>${q.domain}</span><span>${q.topic}</span><span>덤프 Q${q.sourceQuestion}</span>${multi?'<span>복수 선택</span>':''}</div><div class="qnum">QUESTION ${String(index+1).padStart(2,'0')}</div><h2>${q.question}</h2>${multi?'<p class="multi-note">정답을 모두 선택한 뒤 선택 확정을 누르세요.</p>':''}<div class="choices">${q.choices.map((c,i)=>`<button data-i="${i}" class="${a?.choices?.includes(i)?'selected':''}" ${locked?'disabled':''}><i>${String.fromCharCode(65+i)}</i><span>${c}</span></button>`).join('')}</div>${multi&&!locked&&mode!=='exam'?'<button class="confirm-answer" id="confirmAnswer">선택 확정</button>':''}${locked?feedback(q,a):''}<div class="qnav"><button class="btn ghost" id="prev" ${index===0?'disabled':''}>이전</button>${index===queue.length-1?`<button class="btn" id="submit">${mode==='exam'?'답안 제출':'결과 보기'}</button>`:`<button class="btn" id="next">다음</button>`}</div></article>`;document.querySelectorAll('.choices button').forEach(b=>b.onclick=()=>choose(+b.dataset.i));const c=$('confirmAnswer');if(c)c.onclick=confirmMulti;$('prev').onclick=()=>{index--;render()};const n=$('next');if(n)n.onclick=()=>{index++;render()};const s=$('submit');if(s)s.onclick=submit}
function choose(choice){const q=queue[index],multi=Array.isArray(q.answers);if(multi){const selected=new Set(answers[index]?.choices||[]);selected.has(choice)?selected.delete(choice):selected.add(choice);answers[index]={choices:[...selected],locked:mode==='exam'}}else{answers[index]={choices:[choice],locked:mode!=='exam'};if(mode!=='exam')setWrong(q.id,!isCorrect(q,answers[index]))}render()}
function confirmMulti(){const q=queue[index],a=answers[index];if(!a?.choices.length)return;answers[index]={...a,locked:true};setWrong(q.id,!isCorrect(q,answers[index]));render()}
function feedback(q,a){const ok=isCorrect(q,a);return `<div class="feedback ${ok?'ok':'no'}"><b>${ok?'정답입니다':`오답입니다 · 정답 ${letters(q)}`}</b><p>${q.explanation}</p></div>`}
function submit(){if(submitted)return;submitted=true;clearInterval(timerId);queue.forEach((q,i)=>setWrong(q.id,!isCorrect(q,answers[i])));const correct=queue.filter((q,i)=>isCorrect(q,answers[i])).length,pct=Math.round(correct/queue.length*100);if(mode==='exam')saveHistory({date:new Date().toISOString(),correct,total:queue.length,pct});$('quizArea').hidden=true;$('quizBar').hidden=true;$('timer').hidden=true;$('resultArea').hidden=false;$('resultArea').innerHTML=`<p class="eyebrow">RESULT</p><h2>${correct} / ${queue.length}</h2><strong class="result-score">${pct}점</strong><p>${pct>=70?'합격 기준을 넘었습니다.':'70점을 목표로 오답을 복습하세요.'}</p><div class="result-list">${queue.map((q,i)=>`<details class="${isCorrect(q,answers[i])?'pass':'miss'}"><summary>${i+1}. ${q.question}<b>${isCorrect(q,answers[i])?'정답':'오답'}</b></summary><p>덤프 Q${q.sourceQuestion} · 정답: ${letters(q)}</p><p>${q.explanation}</p></details>`).join('')}</div><div class="actions"><a class="btn" href="quiz.html?mode=${mode}">다시 풀기</a><a class="btn ghost" href="quiz.html?mode=wrong">오답 복습</a></div>`}
function startTimer(){$('timer').hidden=false;tick();timerId=setInterval(()=>{remaining--;tick();if(remaining<=0)submit()},1000)}function tick(){const m=String(Math.floor(remaining/60)).padStart(2,'0'),s=String(remaining%60).padStart(2,'0');$('timerText').textContent=`${m}:${s}`}
function fail(msg){$('quizArea').innerHTML=`<div class="empty"><h2>학습을 시작할 수 없습니다</h2><p>${msg}</p><a class="btn" href="index.html">홈으로</a></div>`}init();
