const mode=new URLSearchParams(location.search).get('mode')||'random';
const $=id=>document.getElementById(id);let all=[],queue=[],index=0,answers=[],timerId=null,remaining=2100,submitted=false;
const info={random:['RANDOM PRACTICE','랜덤 10문제','답을 고르면 즉시 정답과 해설을 확인합니다.'],exam:['MOCK EXAM','AZ-900 모의고사','30문제 · 35분 · 모든 답안을 제출한 뒤 채점합니다.'],wrong:['REVIEW','오답노트','이전에 틀린 문제만 다시 풀어 약점을 지웁니다.']};
async function init(){[ $('modeKicker').textContent,$('modeTitle').textContent,$('modeDesc').textContent]=info[mode]||info.random;try{all=await loadQuestions()}catch(e){return fail(e.message)}if(mode==='wrong'){const ids=new Set(getWrongIds());queue=shuffle(all.filter(q=>ids.has(q.id)));if(!queue.length)return fail('저장된 오답이 없습니다. 먼저 랜덤문제나 모의고사를 풀어보세요.')}else queue=shuffle(all).slice(0,mode==='exam'?30:10);answers=Array(queue.length).fill(null);$('quizBar').hidden=false;if(mode==='exam')startTimer();render()}
function render(){const q=queue[index];$('progressText').textContent=`${index+1} / ${queue.length}`;$('scoreText').textContent=mode==='exam'?'답안은 제출 후 공개':`정답 ${answers.filter(a=>a?.correct).length}`;$('progressFill').style.width=`${(index+1)/queue.length*100}%`;const saved=answers[index];$('quizArea').innerHTML=`<article class="question"><div class="qmeta"><span>${q.domain}</span><span>${q.topic}</span></div><div class="qnum">QUESTION ${String(index+1).padStart(2,'0')}</div><h2>${q.question}</h2><div class="choices">${q.choices.map((c,i)=>`<button data-i="${i}" class="${saved?.choice===i?'selected':''}" ${saved&&mode!=='exam'?'disabled':''}><i>${String.fromCharCode(65+i)}</i><span>${c}</span></button>`).join('')}</div>${saved&&mode!=='exam'?feedback(q,saved.choice):''}<div class="qnav"><button class="btn ghost" id="prev" ${index===0?'disabled':''}>이전</button>${index===queue.length-1?`<button class="btn" id="submit">${mode==='exam'?'답안 제출':'결과 보기'}</button>`:`<button class="btn" id="next">다음</button>`}</div></article>`;document.querySelectorAll('.choices button').forEach(b=>b.onclick=()=>choose(+b.dataset.i));$('prev').onclick=()=>{index--;render()};const n=$('next');if(n)n.onclick=()=>{index++;render()};const s=$('submit');if(s)s.onclick=submit}
function choose(choice){const q=queue[index];answers[index]={choice,correct:choice===q.answer};if(mode!=='exam')setWrong(q.id,choice!==q.answer);render()}
function feedback(q,choice){return `<div class="feedback ${choice===q.answer?'ok':'no'}"><b>${choice===q.answer?'정답입니다':'오답입니다 · 정답 '+String.fromCharCode(65+q.answer)}</b><p>${q.explanation}</p>${q.tip?`<small>기억하기 · ${q.tip}</small>`:''}</div>`}
function submit(){if(submitted)return;submitted=true;clearInterval(timerId);queue.forEach((q,i)=>setWrong(q.id,!answers[i]||answers[i].choice!==q.answer));const correct=queue.filter((q,i)=>answers[i]?.choice===q.answer).length,pct=Math.round(correct/queue.length*100);if(mode==='exam')saveHistory({date:new Date().toISOString(),correct,total:queue.length,pct});$('quizArea').hidden=true;$('quizBar').hidden=true;$('timer').hidden=true;$('resultArea').hidden=false;$('resultArea').innerHTML=`<p class="eyebrow">RESULT</p><h2>${correct} / ${queue.length}</h2><strong class="result-score">${pct}점</strong><p>${pct>=70?'합격 기준을 넘었습니다. 틀린 개념만 한 번 더 확인하세요.':'70점을 목표로 오답의 개념을 요약노트에서 복습하세요.'}</p><div class="result-list">${queue.map((q,i)=>`<details class="${answers[i]?.choice===q.answer?'pass':'miss'}"><summary>${i+1}. ${q.question}<b>${answers[i]?.choice===q.answer?'정답':'오답'}</b></summary><p>정답: ${String.fromCharCode(65+q.answer)}. ${q.choices[q.answer]}</p><p>${q.explanation}</p></details>`).join('')}</div><div class="actions"><a class="btn" href="quiz.html?mode=${mode}">다시 풀기</a><a class="btn ghost" href="quiz.html?mode=wrong">오답 복습</a></div>`}
function startTimer(){$('timer').hidden=false;tick();timerId=setInterval(()=>{remaining--;tick();if(remaining<=0)submit()},1000)}function tick(){const m=String(Math.floor(remaining/60)).padStart(2,'0'),s=String(remaining%60).padStart(2,'0');$('timerText').textContent=`${m}:${s}`}
function fail(msg){$('quizArea').innerHTML=`<div class="empty"><h2>학습을 시작할 수 없습니다</h2><p>${msg}</p><a class="btn" href="index.html">홈으로</a></div>`}init();
